<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Stage 2 tables: Ordering (cart, order, payment attempts) and Inventory's
 * Reservation. Boundary rules made visible in DDL:
 *
 *  - inventory_reservation.order_id is a VALUE with a UNIQUE index (that
 *    index IS invariant R1), deliberately NOT a foreign key into
 *    ordering_order — ids cross context boundaries as plain values only
 *    (the part-4 fault line). FKs exist only INSIDE a context, from child
 *    rows to their aggregate root.
 *  - ordering_order stores no total (invariant O2: computed from lines).
 *  - ordering_cart / ordering_cart_line are DBAL-managed (no ORM mapping;
 *    the schema_filter in doctrine.yaml hides them from diff), and cart
 *    lines carry NO price columns (invariant C2).
 *  - ordering_payment_attempt is the fake gateway's PRIVATE ledger — it
 *    persists attempt counts so tok_timeout_once works across separate
 *    HTTP requests.
 */
final class Version20260719002000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Ordering context (cart, order, payment attempts) + Inventory reservations';
    }

    public function up(Schema $schema): void
    {
        // --- ORM-mapped aggregates (generated by doctrine:migrations:diff) ---
        $this->addSql('CREATE TABLE inventory_reservation (order_id VARCHAR(36) NOT NULL, status VARCHAR(10) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, id VARCHAR(36) NOT NULL, UNIQUE INDEX uniq_inventory_reservation_order (order_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE inventory_reservation_line (sku VARCHAR(32) NOT NULL, quantity INT NOT NULL, id INT AUTO_INCREMENT NOT NULL, reservation_id VARCHAR(36) NOT NULL, INDEX IDX_EB865AC1B83297E7 (reservation_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE ordering_order (customer_id VARCHAR(64) NOT NULL, status VARCHAR(10) NOT NULL, currency VARCHAR(3) NOT NULL, placed_at DATETIME NOT NULL, paid_at DATETIME DEFAULT NULL, shipped_at DATETIME DEFAULT NULL, cancelled_at DATETIME DEFAULT NULL, transaction_id VARCHAR(64) DEFAULT NULL, id VARCHAR(36) NOT NULL, INDEX idx_ordering_order_customer_placed (customer_id, placed_at), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE ordering_order_line (sku VARCHAR(32) NOT NULL, name VARCHAR(255) NOT NULL, quantity INT NOT NULL, id INT AUTO_INCREMENT NOT NULL, unit_price_minor INT NOT NULL, unit_price_currency VARCHAR(3) NOT NULL, order_id VARCHAR(36) NOT NULL, INDEX IDX_CDF59D4E8D9F6D38 (order_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('ALTER TABLE inventory_reservation_line ADD CONSTRAINT FK_EB865AC1B83297E7 FOREIGN KEY (reservation_id) REFERENCES inventory_reservation (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE ordering_order_line ADD CONSTRAINT FK_CDF59D4E8D9F6D38 FOREIGN KEY (order_id) REFERENCES ordering_order (id) ON DELETE CASCADE');

        // --- DBAL-managed tables (no ORM mapping on purpose) -----------------
        $this->addSql('CREATE TABLE ordering_cart (customer_id VARCHAR(64) NOT NULL, currency VARCHAR(3) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, PRIMARY KEY (customer_id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE ordering_cart_line (cart_id VARCHAR(64) NOT NULL, sku VARCHAR(32) NOT NULL, quantity INT NOT NULL, PRIMARY KEY (cart_id, sku), CONSTRAINT FK_ordering_cart_line_cart FOREIGN KEY (cart_id) REFERENCES ordering_cart (customer_id) ON DELETE CASCADE) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE ordering_payment_attempt (id INT AUTO_INCREMENT NOT NULL, order_id VARCHAR(36) NOT NULL, attempt_no INT NOT NULL, token VARCHAR(64) NOT NULL, outcome VARCHAR(32) NOT NULL, created_at DATETIME NOT NULL, INDEX idx_payment_attempt_order (order_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE ordering_payment_attempt');
        $this->addSql('DROP TABLE ordering_cart_line');
        $this->addSql('DROP TABLE ordering_cart');
        $this->addSql('ALTER TABLE inventory_reservation_line DROP FOREIGN KEY FK_EB865AC1B83297E7');
        $this->addSql('ALTER TABLE ordering_order_line DROP FOREIGN KEY FK_CDF59D4E8D9F6D38');
        $this->addSql('DROP TABLE inventory_reservation');
        $this->addSql('DROP TABLE inventory_reservation_line');
        $this->addSql('DROP TABLE ordering_order');
        $this->addSql('DROP TABLE ordering_order_line');
    }
}
