<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * The full part-2 schema: user, team, team_membership, task, comment,
 * api_token -- with the FK cascade rules (team/task deletes cascade,
 * task.assignee_id SET NULL) and the team-scoped composite indexes from the
 * PRD. Generated by doctrine:migrations:diff from the entity mapping, then
 * reviewed against the PRD table definitions.
 */
final class Version20260718212519 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Create user, team, team_membership, task, comment and api_token tables';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE api_token (id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, token_hash CHAR(64) CHARACTER SET ascii NOT NULL COLLATE `ascii_bin`, name VARCHAR(100) NOT NULL, created_at DATETIME NOT NULL, last_used_at DATETIME DEFAULT NULL, user_id BIGINT UNSIGNED NOT NULL, INDEX IDX_7BA2F5EBA76ED395 (user_id), UNIQUE INDEX uniq_api_token_hash (token_hash), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE comment (id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, body LONGTEXT NOT NULL, created_at DATETIME NOT NULL, task_id BIGINT UNSIGNED NOT NULL, author_id BIGINT UNSIGNED NOT NULL, INDEX IDX_9474526CF675F31B (author_id), INDEX idx_comment_task (task_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE task (id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, title VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, status VARCHAR(20) DEFAULT \'todo\' NOT NULL, priority VARCHAR(10) DEFAULT \'medium\' NOT NULL, due_date DATE DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, team_id BIGINT UNSIGNED NOT NULL, assignee_id BIGINT UNSIGNED DEFAULT NULL, created_by_id BIGINT UNSIGNED NOT NULL, INDEX IDX_527EDB25296CD8AE (team_id), INDEX IDX_527EDB2559EC7D60 (assignee_id), INDEX IDX_527EDB25B03A8386 (created_by_id), INDEX idx_task_team_status (team_id, status), INDEX idx_task_team_assignee (team_id, assignee_id), INDEX idx_task_team_created (team_id, created_at), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE team (id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, name VARCHAR(100) NOT NULL, created_at DATETIME NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE team_membership (id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, role VARCHAR(10) NOT NULL, created_at DATETIME NOT NULL, user_id BIGINT UNSIGNED NOT NULL, team_id BIGINT UNSIGNED NOT NULL, INDEX IDX_B826A040A76ED395 (user_id), INDEX idx_membership_team (team_id), UNIQUE INDEX uniq_membership (user_id, team_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('CREATE TABLE `user` (id BIGINT UNSIGNED AUTO_INCREMENT NOT NULL, email VARCHAR(180) NOT NULL, password_hash VARCHAR(255) NOT NULL, display_name VARCHAR(100) NOT NULL, created_at DATETIME NOT NULL, UNIQUE INDEX uniq_user_email (email), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4');
        $this->addSql('ALTER TABLE api_token ADD CONSTRAINT FK_7BA2F5EBA76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE comment ADD CONSTRAINT FK_9474526C8DB60186 FOREIGN KEY (task_id) REFERENCES task (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE comment ADD CONSTRAINT FK_9474526CF675F31B FOREIGN KEY (author_id) REFERENCES `user` (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE task ADD CONSTRAINT FK_527EDB25296CD8AE FOREIGN KEY (team_id) REFERENCES team (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE task ADD CONSTRAINT FK_527EDB2559EC7D60 FOREIGN KEY (assignee_id) REFERENCES `user` (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE task ADD CONSTRAINT FK_527EDB25B03A8386 FOREIGN KEY (created_by_id) REFERENCES `user` (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE team_membership ADD CONSTRAINT FK_B826A040A76ED395 FOREIGN KEY (user_id) REFERENCES `user` (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE team_membership ADD CONSTRAINT FK_B826A040296CD8AE FOREIGN KEY (team_id) REFERENCES team (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE api_token DROP FOREIGN KEY FK_7BA2F5EBA76ED395');
        $this->addSql('ALTER TABLE comment DROP FOREIGN KEY FK_9474526C8DB60186');
        $this->addSql('ALTER TABLE comment DROP FOREIGN KEY FK_9474526CF675F31B');
        $this->addSql('ALTER TABLE task DROP FOREIGN KEY FK_527EDB25296CD8AE');
        $this->addSql('ALTER TABLE task DROP FOREIGN KEY FK_527EDB2559EC7D60');
        $this->addSql('ALTER TABLE task DROP FOREIGN KEY FK_527EDB25B03A8386');
        $this->addSql('ALTER TABLE team_membership DROP FOREIGN KEY FK_B826A040A76ED395');
        $this->addSql('ALTER TABLE team_membership DROP FOREIGN KEY FK_B826A040296CD8AE');
        $this->addSql('DROP TABLE api_token');
        $this->addSql('DROP TABLE comment');
        $this->addSql('DROP TABLE task');
        $this->addSql('DROP TABLE team');
        $this->addSql('DROP TABLE team_membership');
        $this->addSql('DROP TABLE `user`');
    }
}
